openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST HTTP API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: HTTP
paths:
  /http/:
    get:
      tags:
      - HTTP
      summary: NGINX Return List of HTTP-Related Endpoints
      description: Returns a list of first level HTTP endpoints.
      operationId: getHttp
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getHttp200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfStrings'
              example:
              - nginx
              - processes
              - connections
              - slabs
              - http
              - stream
              - ssl
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getHttp404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ArrayOfStrings:
      title: Array
      description: 'An array of strings.

        '
      type: array
      items:
        type: string
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
