openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST Connections API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: Connections
paths:
  /connections:
    get:
      tags:
      - Connections
      summary: NGINX Return Client Connections Statistics
      description: Returns statistics of client connections.
      operationId: getConnections
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getConnections200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxConnections'
              example:
                accepted: 4968119
                dropped: 0
                active: 5
                idle: 117
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getConnections404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      parameters:
      - in: query
        name: fields
        description: Limits which fields of the connections statistics will be output.
        x-example: ''
        schema:
          type: string
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - Connections
      summary: NGINX Reset Client Connections Statistics
      description: Resets statistics of accepted and dropped client connections.
      operationId: deleteConnections
      responses:
        '204':
          description: Success
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: deleteConnections404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: deleteConnections405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
    NginxConnections:
      title: Connections
      description: 'The number of accepted, dropped, active, and idle connections.

        '
      type: object
      properties:
        accepted:
          type: integer
          description: The total number of accepted client connections.
          example: 4968119
        dropped:
          type: integer
          description: The total number of dropped client connections.
          example: 0
        active:
          type: integer
          description: The current number of active client connections.
          example: 5
        idle:
          type: integer
          description: The current number of idle client connections.
          example: 117
      example:
        accepted: 4968119
        dropped: 0
        active: 5
        idle: 117
