openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST Stream Zone Sync API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: Stream Zone Sync
paths:
  /stream/zone_sync/:
    get:
      tags:
      - Stream Zone Sync
      summary: NGINX Return Sync Status of a Node
      description: Returns synchronization status of a cluster node.
      operationId: getStreamZoneSync
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getStreamZoneSync200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxStreamZoneSync'
              example:
                zones:
                  zone1:
                    records_pending: 2061
                    records_total: 260575
                  zone2:
                    records_pending: 0
                    records_total: 14749
                status:
                  bytes_in: 1364923761
                  msgs_in: 337236
                  msgs_out: 346717
                  bytes_out: 1402765472
                  nodes_online: 15
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getStreamZoneSync404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxStreamZoneSync:
      title: Stream Zone Sync Node
      type: object
      properties:
        zones:
          type: object
          title: Zone Sync Zones
          description: Synchronization information per each shared memory zone.
          additionalProperties:
            $ref: '#/components/schemas/NginxStreamZoneSyncZone'
          example: {}
        status:
          type: object
          description: Synchronization information per node in a cluster.
          properties:
            bytes_in:
              type: integer
              description: The number of bytes received by this node.
              example: 0
            msgs_in:
              type: integer
              description: The number of messages received by this node.
              example: 0
            msgs_out:
              type: integer
              description: The number of messages sent by this node.
              example: 0
            bytes_out:
              type: integer
              description: The number of bytes sent by this node.
              example: 0
            nodes_online:
              type: integer
              description: The number of peers this node is connected to.
              example: 0
          example: 200
      example:
        zones:
          zone1:
            records_pending: 2061
            records_total: 260575
          zone2:
            records_pending: 0
            records_total: 14749
        status:
          bytes_in: 1364923761
          msgs_in: 337236
          msgs_out: 346717
          bytes_out: 1402765472
          nodes_online: 15
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
    NginxStreamZoneSyncZone:
      title: Sync Zone
      description: Synchronization status of a shared memory zone.
      type: object
      properties:
        records_pending:
          type: integer
          description: The number of records that need to be sent to the cluster.
          example: 0
        records_total:
          type: integer
          description: The total number of records stored in the shared memory zone.
          example: 0
