openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST HTTP Limit Reqs API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: HTTP Limit Reqs
paths:
  /http/limit_reqs/:
    get:
      tags:
      - HTTP Limit Reqs
      summary: NGINX Return Status of All HTTP Limit_req Zones
      description: Returns status information for each HTTP [limit_req zone](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone).
      operationId: getHttpLimitReqZones
      parameters:
      - in: query
        name: fields
        description: Limits which fields of limit_req zones will be output. If the “<literal>fields</literal>” value is empty, then only zone names will be output.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getHttpLimitReqZones200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxHTTPLimitReqZonesMap'
              example: example
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getHttpLimitReqZones404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /http/limit_reqs/{httpLimitReqZoneName}:
    parameters:
    - name: httpLimitReqZoneName
      in: path
      description: The name of a [limit_req zone](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone).
      required: true
      x-example: example_httpLimitReqZoneName
      schema:
        type: string
    get:
      tags:
      - HTTP Limit Reqs
      summary: NGINX Return Status of an HTTP Limit_req Zone
      description: Returns status of a particular HTTP [limit_req zone](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone).
      operationId: getHttpLimitReqZone
      parameters:
      - name: fields
        in: query
        description: Limits which fields of the [limit_req zone](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone) will be output.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getHttpLimitReqZone200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxHTTPLimitReqZone'
              example:
                passed: 15
                delayed: 4
                rejected: 0
                delayed_dry_run: 1
                rejected_dry_run: 2
        '404':
          description: 'limit_req not found (*LimitReqNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: getHttpLimitReqZone404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - HTTP Limit Reqs
      summary: NGINX Reset Statistics for an HTTP Limit_req Zone
      description: Resets the requests limiting statistics.
      operationId: deleteHttpLimitReqZoneStat
      responses:
        '204':
          description: Success
        '404':
          description: 'limit_req not found (*LimitReqNotFound*),

            unknown version (*UnknownVersion*)

            '
          x-microcks-refs:
          - name: deleteHttpLimitReqZoneStat404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: deleteHttpLimitReqZoneStat405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxHTTPLimitReqZone:
      title: HTTP Requests Rate Limiting
      type: object
      properties:
        passed:
          type: integer
          description: The total number of requests that were neither limited nor accounted as limited.
          example: 0
        delayed:
          type: integer
          description: The total number of requests that were delayed.
          example: 0
        rejected:
          type: integer
          description: The total number of requests that were rejected.
          example: 0
        delayed_dry_run:
          type: integer
          description: The total number of requests accounted as delayed in the <a href="https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_dry_run">dry run</a> mode.
          example: 0
        rejected_dry_run:
          type: integer
          description: The total number of requests accounted as rejected in the <a href="https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_dry_run">dry run</a> mode.
          example: 0
      example:
        passed: 15
        delayed: 4
        rejected: 0
        delayed_dry_run: 1
        rejected_dry_run: 2
    NginxHTTPLimitReqZonesMap:
      title: HTTP limit_reqs
      description: 'Status data for all HTTP

        <a href="https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone">limit_req zones</a>.

        '
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NginxHTTPLimitReqZone'
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
