openapi: 3.2.0
info:
  version: '9.0'
  title: NGINX Plus REST HTTP Requests API
  description: NGINX Plus REST [API](https://nginx.org/en/docs/http/ngx_http_api_module.html) provides access to NGINX Plus status information, on-the-fly configuration of upstream servers and key-value pairs management for [http](https://nginx.org/en/docs/http/ngx_http_keyval_module.html) and [stream](https://nginx.org/en/docs/stream/ngx_stream_keyval_module.html).
servers:
- url: /api/9
tags:
- name: HTTP Requests
paths:
  /http/requests:
    get:
      tags:
      - HTTP Requests
      summary: NGINX Return HTTP Requests Statistics
      description: Returns status of client HTTP requests.
      operationId: getHttpRequests
      parameters:
      - in: query
        name: fields
        description: Limits which fields of client HTTP requests statistics will be output.
        x-example: ''
        schema:
          type: string
      responses:
        '200':
          description: Success
          x-microcks-refs:
          - name: getHttpRequests200Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxHTTPRequests'
              example:
                total: 10624511
                current: 4
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: getHttpRequests404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      tags:
      - HTTP Requests
      summary: NGINX Reset HTTP Requests Statistics
      description: Resets the number of total client HTTP requests.
      operationId: deleteHttpRequests
      responses:
        '204':
          description: Success
        '404':
          description: Unknown version (*UnknownVersion*)
          x-microcks-refs:
          - name: deleteHttpRequests404Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
        '405':
          description: Method disabled (*MethodDisabled*)
          x-microcks-refs:
          - name: deleteHttpRequests405Example
            x-microcks-default: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NginxError'
              example:
                error: {}
                request_id: example-request_id
                href: example-href
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    NginxError:
      title: Error
      description: 'nginx error object.

        '
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
              description: HTTP error code.
              example: 200
            text:
              type: string
              description: Error description.
              example: example-text
            code:
              type: string
              description: Internal nginx error code.
              example: 200
          example: {}
        request_id:
          type: string
          description: The ID of the request, equals the value of the <a href="https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id">$request_id</a> variable.
          example: example-request_id
        href:
          type: string
          description: Link to reference documentation.
          example: example-href
    NginxHTTPRequests:
      title: HTTP Requests
      type: object
      properties:
        total:
          type: integer
          description: The total number of client requests.
          example: 98765
        current:
          type: integer
          description: The current number of client requests.
          example: 3
      example:
        total: 10624511
        current: 4
